### ISSUE TITLE
Ovčín

### ISSUE THREAD

**Issue by Ratchet97** [LynSisCZ/Evelynn#11]
Zdravím,

chtěl bych napsat pár slovních spojení a věty referujících na Ovčín, které by Evelynn detekovala v chatu a hráče navedla na Ovčín.

- [x] ''je na serveru nějaká veřejná střižna vlny?''
- [x] ''je někde veřejná střižna vlny?''
- [x] ''je na mapě nějaká veřejná střižna vlny?''
- [x] ''je tu střižna vlny?''
- [x] ''kde je střižna vlny?''
- [x] ''střižna vlny''
- [x] ''kde si mohu nastříhat vlnu?''
- [x] ''farma na vlnu''
- [ ] ''vlnárna''
- [x] ''kde je vlnárna?''
- [x] ''kudy na ovčín?''
- [ ] ''Ovčín''
- [x] ''kde jsou veřejné farmy?''
- [x] ''jsou tu veřejné farmy?''
- [x] ''Veřejné farmy''
- [x] ''jak se dostanu do ovčína''

//Edit: odstraněny duplicity, upraveno na checklist -Pozitrone

Na všechny tyto zprávy by Evelynn mohla vypsat větu: ''Veřejnou střižnu vlny a veřejné farmy najdeš v Ovčíně. Dostaneš se tam směrem po východním (tyrkysovém) CNC a k portálu vede duhový tunel.''

**Comment by Ratchet97** [comment]
Teď jsem si uvědomil, že ta východní linka není modrá, ale tyrkysová (cyan).

**Comment by Pozitrone** [comment]
// Dvoj-commit protože githubu zase jeblo a nechtěl povolit push... nakopat...
každopádně, je to tam ;)
